[package]
name = "backend-adapter-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
backend-core = { path = "../backend-core", features = ["tokio"] }